import type { Metadata } from "next";
import Header from "../shared/components/sections/Header";
import { Sidebar } from "../shared/components/sections/Sidebar";
import ClientInitialize from "./ClientInitialize";
import "./globals.css";
import { Providers } from "./Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1"
      />
      <body className="bg-black text-white h-screen">
        <Providers>
          <ClientInitialize />
          <div className="flex min-h-full">
            <Sidebar />
            <div className="flex-1 flex flex-col">
              <Header />
              <main className="flex px-12 pb-18 pt-4 overflow-auto h-full w-full justify-center">
                {children}
              </main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
