import type { Metadata } from "next";
import { Sidebar } from "../shared/components/sections/Sidebar";
import ClientInitialize from "./ClientInitialize";
import "./globals.css";
import { Providers } from "./Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1"
      />
      <body className="bg-black text-white">
        <Providers>
          <ClientInitialize />
          <div className="flex min-h-screen">
            <Sidebar />
            <main className="flex-1 px-12 py-8 overflow-auto">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
